# fly.toml app configuration file generated for welcome-muddy-smoke-3251 on 2024-08-20T21:25:18+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'welcome-muddy-smoke-3251'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.status]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  size = 'shared-cpu-1x'
